apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-service
  namespace: stockmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: stockmgr
      app: emp-service
  template:
    metadata:
      labels:
        project: stockmgr
        app: emp-service
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: emp-service
          image: registry.cn-hangzhou.aliyuncs.com/my-stock-dio/emp-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 8030
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g"
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 8030
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8030
            initialDelaySeconds: 60
            periodSeconds: 10
