kind: List
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: login
      namespace: stockmgr
    spec:
      type: NodePort
      selector:
        app: login
      ports:
        - name: http
          port: 8099
          targetPort: 8099
          nodePort: 30100
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: login
      namespace: stockmgr
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: login
      template:
        metadata:
          labels:
            app: login
        spec:
          containers:
            - name: login
              imagePullPolicy: IfNotPresent
              image: registry.cn-hangzhou.aliyuncs.com/my-stock-dio/login:latest
              ports:
                - containerPort: 8099

