server:
  port: 9999
spring:
  application:
    name: @artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          #开启以服务id去注册中心上获取转发地址
          enabled: true
          ##小写serviceId
          lower-case-service-id: true
      routes:
        - id: product-client
          uri: lb://product-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/product/**
        - id: dept-client
          uri: lb://dept-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/dept/**
        - id: emp-client
          uri: lb://emp-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/emp/**

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka