server:
  port: 8030
spring:

  application:
    name: emp-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tb_product?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: oku200309 #在这里填入自己的mysql密码
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: false


  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka