server:
  port: 8888
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 #续约时间间隔（秒）
    lease-expiration-duration-in-seconds: 15 #续约到期时间（秒）
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000
    wait-time-in-ms-when-sync-empty: 0
    responseCacheUpdateIntervalMs: 1
    use-read-only-response-cache: false
    renewal-percent-threshold: 0.49
  client:
    healthcheck.enabled: false
    onDemandUpdateStatusChange: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false