eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #续约时间间隔（秒）
    lease-expiration-duration-in-seconds: 15 #续约到期时间（秒）
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000
    wait-time-in-ms-when-sync-empty: 0
    responseCacheUpdateIntervalMs: 1
    use-read-only-response-cache: false
    renewal-percent-threshold: 0.49
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service.stockmgr.svc.cluster.local:8888/eureka
    fetch-registry: false
